### ISSUE TITLE
Support for this product?

### ISSUE THREAD

**Issue by JohanBendz** [AutomateAsia/com.yale.lock#1]
Hi there. Nice work with the app!

Will you guys be able to add support for the V2N lock?
https://www.yale.se/sv/yale/yalese/produkter/yale-doorman/yale-doorman-v2n-digitalt-dorrlas/

Best regards, Johan.

**Comment by addwindtan** [comment]
Hi Johan,

Thanks for the encouragement!

We would love to add support for the V2N lock. Unfortunately, we don't have one at the moment.

Best Regards,
Edwin
