### ISSUE TITLE
au yrd220

### ISSUE THREAD

**Issue by tiimbo82** [AutomateAsia/com.yale.lock#2]
![yale](https://user-images.githubusercontent.com/36907258/37860495-6c81040c-2f7a-11e8-8ba6-a572128f4192.png)
 hey guys, any chance of supporting this, the id's line up but it is still unsupported.
cheers

tim

**Comment by tiimbo82** [comment]
Thanks for adding, unfortunately the Yale app just crashes now

**Comment by limkopi78** [comment]
Hi, the ID looks quite odd to be 0000. Does pairing again show a different ID?

**Comment by limkopi78** [comment]
May I know if the app is working on your end now?

**Comment by tiimbo82** [comment]
Sorry I moved on from homey, in Australia there wasn't enough zwave devices
supported
