### ISSUE TITLE
I set up the ydd424 fine but now can't register.

### ISSUE THREAD

**Issue by aarontaycheehsien** [AutomateAsia/com.yale.lock#5]
I set up the ydd424 with honey and it works fine.

The main difference is my lock manual says press #9 instead of #7.

But when I tried to unregister the controller  on my Yale  lock it stalls after I enter my master pin the 2nd time.

Any ideas?

**Comment by limkopi78** [comment]
It is a common Z-Wave pairing issue. Usually will be resolved with an unpair and pair.
